services:
  mysql:
    image: mysql:8.4.1
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project1
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  myapp:
    build:
      context: ./backend/project1
      dockerfile: Dockerfile
      args:
        - 'JAR_FILE=build/libs/\*.jar'
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project1
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 1234
      IMAGE_UPLOAD_DIRECTORY: ./uploaded_images
      MAIL_USERNAME: mail@mail.com
      MAIL_PASSWORD: mailpassword
