spring:
  application.name: project1
  datasource:
    url: jdbc:mysql://localhost:3306/project1
    username: dbuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: qwerasdfzxcvqwer  # 앱 비밀번호 또는 OAuth 발급 토큰
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
