spring:
  application.name: project1
  datasource:
    url: jdbc:mysql://localhost:3306/project1
    username: dbuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
