spring:
  application.name: project1

  datasource:
    url: jdbc:mysql://localhost:3306/project1
    username: dbuser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  servlet:
    multipart:
      # 이미지 크기 제한
      max-file-size: 256KB
      # 이미지를 포함한 multipart 요청 크기 제한
      max-request-size: 256KB

# 상품 이미지를 저장할 경로 지정
file.upload-dir: ${IMAGE_UPLOAD_DIRECTORY}
