spring:
  application.name: project1
  datasource:
    url: jdbc:mysql://localhost:3306/project1
    username: dbuser
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

